apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kf-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kf-api
  minReplicas: 10
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
